// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phlcktaeiuqwqhfmtszx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBobGNrdGFlaXVxd3FoZm10c3p4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2NzU0MzgsImV4cCI6MjA2MjI1MTQzOH0.7Eb7Y2SvOSfETQhLMFyM_1XlGepO3_ORCM-itF7lsyw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);